# Generated by Django 5.1.3 on 2024-11-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensemanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category_option', models.CharField(choices=[('food', 'food'), ('travel', 'travel'), ('entertaiment', 'entertaiment'), ('other', 'other')], default='food', max_length=200)),
                ('amount', models.PositiveIntegerField()),
                ('payment_option', models.CharField(choices=[('Card', 'Card'), ('Cash', 'Cash'), ('UPI', 'UPI')], default='card', max_length=200)),
            ],
        ),
    ]
